type: object
title: Action
minProperties: 1
maxProperties: 1
description: ""
properties:
  tab_close:
    type: boolean
  tab_close_all:
    type: boolean
  tab_open:
    type: boolean
  tab_duplicate:
    type: boolean
  tab_next:
    type: boolean
  tab_previous:
    type: boolean
  go_forward:
    type: object
    properties:
      action:
        type: boolean
    required:
      - action
  go_backward:
    type: object
    properties:
      action:
        type: boolean
    required:
      - action
  reload:
    type: boolean
  javascript_run:
    type: object
    properties:
      description:
        type: string
      code:
        type: string
    required:
      - code
  url_copy:
    type: boolean
  scroll_top:
    type: boolean
  scroll_bottom:
    type: boolean
